name: try_flutter_deck
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_deck: ^0.14.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/

